### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by scollovati** [smachaje/LTIPHPMembership#1]
Hi Simon,
I have two questions about the setup:

> 1. Create a MySQL database based on the parent project and SQL in src/sql directory

Where is the folder src/sql? I assume that there we'll find the sql queries for generating the tables.
   

> 4. Create a placement as course tool in Blackboard (Web Link will not expose the membership service)

What will be the placement URL (excluding the FQDN)?

**Comment by smachaje** [comment]
You’ll find the sql dir here: https://github.com/celtic-project/LTI-PHP/tree/master/sql

The placement URL is configured in the LMS and would be the URL of your custom app.
